import * as LucideIcons from 'lucide-react';
import { LucideIcon } from 'lucide-react';

export const IconMap: Record<string, LucideIcon> = {
  LayoutDashboard: LucideIcons.LayoutDashboard,
  Package: LucideIcons.Package,
  ShoppingCart: LucideIcons.ShoppingCart,
  Users: LucideIcons.Users,
  Settings: LucideIcons.Settings,
  LogOut: LucideIcons.LogOut,
  Bell: LucideIcons.Bell,
  Search: LucideIcons.Search,
  Menu: LucideIcons.Menu,
  X: LucideIcons.X,
  UserCog: LucideIcons.UserCog,
  Box: LucideIcons.Box,
  Sparkles: LucideIcons.Sparkles,
  Calendar: LucideIcons.Calendar,
  Warehouse: LucideIcons.Warehouse,
  BarChart2: LucideIcons.BarChart2,
  Activity: LucideIcons.Activity,
  DollarSign: LucideIcons.DollarSign,
  CreditCard: LucideIcons.CreditCard,
  HeartPulse: LucideIcons.HeartPulse,
  Tags: LucideIcons.Tags,
  Monitor: LucideIcons.Monitor,
  Star: LucideIcons.Star,
  Clock: LucideIcons.Clock,
  Building2: LucideIcons.Building2,
  Receipt: LucideIcons.Receipt,
  Save: LucideIcons.Save,
  RefreshCw: LucideIcons.RefreshCw,
  Shield: LucideIcons.Shield,
  Palette: LucideIcons.Palette,
  HardDrive: LucideIcons.HardDrive,
  Smartphone: LucideIcons.Smartphone,
  Globe: LucideIcons.Globe,
  Mail: LucideIcons.Mail,
  Phone: LucideIcons.Phone,
  CheckCircle2: LucideIcons.CheckCircle2,
  AlertCircle: LucideIcons.AlertCircle,
  FileText: LucideIcons.FileText,
  Briefcase: LucideIcons.Briefcase,
  PieChart: LucideIcons.PieChart,
  Target: LucideIcons.Target,
  Award: LucideIcons.Award,
  BookOpen: LucideIcons.BookOpen,
  Coffee: LucideIcons.Coffee,
  Compass: LucideIcons.Compass,
  Gift: LucideIcons.Gift,
  Key: LucideIcons.Key,
  Link: LucideIcons.Link,
  Map: LucideIcons.Map,
  Music: LucideIcons.Music,
  Video: LucideIcons.Video,
  Camera: LucideIcons.Camera,
  Folder: LucideIcons.Folder,
  Home: LucideIcons.Home,
  MessageSquare: LucideIcons.MessageSquare,
  Send: LucideIcons.Send,
  Share2: LucideIcons.Share2,
  ThumbsUp: LucideIcons.ThumbsUp,
  TrendingUp: LucideIcons.TrendingUp,
  Zap: LucideIcons.Zap,
};

export const getIcon = (name: string): LucideIcon => {
  return IconMap[name] || LucideIcons.HelpCircle;
};
