export const defaultNavItems = [
  { name: "TỔNG QUAN", iconName: "LayoutDashboard", path: "/", module: "Dashboard" },
  {
    name: "POS BÁN HÀNG",
    iconName: "ShoppingCart",
    path: "/orders",
    module: "POS BÁN HÀNG",
    subItems: [
      { name: "Tạo đơn hàng", path: "/orders/create" },
      { name: "Hóa đơn", path: "/orders" },
      { name: "Thanh toán", path: "/orders/payments" },
      { name: "Công nợ", path: "/orders/debts" },
    ],
  },
  {
    name: "CRM KHÁCH HÀNG",
    iconName: "Users",
    path: "/customers",
    module: "CRM KHÁCH HÀNG",
    subItems: [
      { name: "Khách hàng", path: "/customers" },
      { name: "Referral", path: "/customers/referrers" },
      { name: "Thành viên", path: "/customers/loyalty" },
    ],
  },
  {
    name: "LỊCH HẸN",
    iconName: "Calendar",
    path: "/appointments",
    module: "LỊCH HẸN",
    subItems: [
      { name: "Danh sách lịch hẹn", path: "/appointments" },
      { name: "Lịch hôm nay", path: "/appointments/calendar" },
      { name: "Lịch nhân viên", path: "/appointments/staff" },
      { name: "Nhân viên", path: "/appointments/staff-config" },
      { name: "Phòng dịch vụ", path: "/appointments/rooms" },
    ],
  },
  {
    name: "SỨC KHỎE & LIỆU TRÌNH",
    iconName: "HeartPulse",
    path: "/health",
    module: "SỨC KHỎE",
    subItems: [
      { name: "Hồ sơ sức khỏe", path: "/health/records" },
      { name: "Liệu trình", path: "/health/treatments" },
      { name: "Nhật ký trị liệu", path: "/health/logs" },
      { name: "Kết quả đánh giá", path: "/health/evaluations" },
    ],
  },
  {
    name: "SẢN PHẨM & DỊCH VỤ",
    iconName: "Sparkles",
    path: "/products",
    module: "SẢN PHẨM & DỊCH VỤ",
    subItems: [
      { name: "Sản phẩm", path: "/products" },
      { name: "Dịch vụ", path: "/services" },
      { name: "Danh mục", path: "/products/categories" },
      { name: "Cấu hình", path: "/products/settings" },
    ],
  },
  {
    name: "KHO",
    iconName: "Warehouse",
    path: "/inventory",
    module: "KHO",
    subItems: [
      { name: "Kho hàng", path: "/inventory/stock" },
      { name: "Giao dịch kho", path: "/inventory/transactions" },
      { name: "Nhà cung cấp", path: "/inventory/suppliers" },
    ],
  },
  {
    name: "NHÂN SỰ",
    iconName: "UserCog",
    path: "/users",
    module: "Nhân sự",
    subItems: [
      { name: "Danh sách nhân viên", path: "/users" },
      { name: "Chấm công", path: "/users/timesheets" },
      { name: "Lịch làm việc", path: "/users/schedules" },
      { name: "KPI & Hiệu suất", path: "/users/kpi" },
      { name: "Hoa hồng", path: "/users/commissions" },
      { name: "Bảng lương", path: "/users/payroll" },
      { name: "Phân quyền", path: "/users/roles" },
      { name: "Đánh giá", path: "/users/evaluations" },
    ],
  },
  {
    name: "MARKETING",
    iconName: "Tags",
    path: "/marketing",
    module: "MARKETING",
    subItems: [
      { name: "Voucher", path: "/customers/vouchers" },
      { name: "Coupon", path: "/marketing/coupons" },
      { name: "Membership", path: "/customers/loyalty-settings" },
      { name: "Affiliate", path: "/customers/commissions" },
    ],
  },
  {
    name: "TÀI CHÍNH",
    iconName: "DollarSign",
    path: "/finances",
    module: "TÀI CHÍNH",
    subItems: [
      { name: "Thu", path: "/finances/incomes" },
      { name: "Chi", path: "/finances/expenses" },
      { name: "Công nợ nội bộ", path: "/finances/debts" },
      { name: "Sổ quỹ", path: "/finances/funds" },
      { name: "Thùng rác tài chính", path: "/finances/trash" },
    ],
  },
  {
    name: "BÁO CÁO",
    iconName: "BarChart2",
    path: "/reports",
    module: "BÁO CÁO",
    subItems: [
      { name: "Dashboard", path: "/reports" },
      { name: "Doanh thu", path: "/reports/revenue" },
      { name: "Sản phẩm", path: "/reports/products" },
      { name: "Dịch vụ", path: "/reports/services" },
      { name: "Nhân viên", path: "/reports/staff" },
      { name: "Referral", path: "/reports/referral" },
      { name: "Thành viên", path: "/reports/loyalty" },
    ],
  },
  {
    name: "HỆ THỐNG",
    iconName: "Settings",
    path: "/settings",
    module: "Hệ thống",
    subItems: [
      { name: "Cài đặt chung", path: "/settings/store" },
      { name: "Cấu hình thanh toán", path: "/settings/payment" },
      { name: "Cấu hình hóa đơn", path: "/settings/invoice" },
      { name: "Thùng rác", path: "/settings/trash" },
      { name: "Nhật ký", path: "/settings/logs" },
      { name: "Sao lưu", path: "/settings/backup" },
      { name: "Khôi phục", path: "/settings/restore" },
    ],
  },
];
